<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Katalon Terms</name>
   <tag></tag>
   <elementGuidId>80561edf-bf80-4c8e-9fc6-3c560249caec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_85550910293']/div[3]/div/form/div[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.hyperlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>12bbf7ec-221a-4c15-9e1c-627fafb6d5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>3c9fa13e-b229-4b5c-9354-475e9d8ed465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/terms/#terms-of-use</value>
      <webElementGuid>7af8aa33-7546-4c08-a489-e8633dc5e88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyperlink</value>
      <webElementGuid>36256218-3e89-4e4c-8413-e38f20fc8197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Terms</value>
      <webElementGuid>0cd24847-7bd9-4eca-9c93-a26bc4006ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_85550910293&quot;)/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]/div[@class=&quot;policy&quot;]/a[@class=&quot;hyperlink&quot;]</value>
      <webElementGuid>2a2c1a07-12bf-4d92-8624-ddef44487575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_85550910293']/div[3]/div/form/div[6]/a</value>
      <webElementGuid>eccf7488-6839-4c5f-8209-27f5e9c5e66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Katalon Terms')]</value>
      <webElementGuid>331bde1e-bd3b-4c55-a095-a05e65437a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do not allow space'])[1]/following::a[1]</value>
      <webElementGuid>c328d238-2d06-4533-a3a0-cdc3ebfd345e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[1]</value>
      <webElementGuid>b3aeef68-58de-4b86-9ee7-4b069c34c92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Katalon'])[4]/preceding::a[2]</value>
      <webElementGuid>16a5567c-5f3c-4434-a68a-1bae0cceb215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Katalon Terms']/parent::*</value>
      <webElementGuid>f11a866e-8d3d-4417-aaae-4bddad7994cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/terms/#terms-of-use')]</value>
      <webElementGuid>ac4934bd-ce75-4a73-87f4-cdae4c84db0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>1cab0ab6-22ac-459b-9028-cd420b27ee82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/terms/#terms-of-use' and (text() = 'Katalon Terms' or . = 'Katalon Terms')]</value>
      <webElementGuid>1c765b37-3127-482c-b639-a03a3bd08f0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
